### ISSUE TITLE
EOFError in processing

### ISSUE THREAD

**Issue by koustuvsinha** [enewe101/cluster-func#3] opened 2017-01-21 16:06 UTC
I am getting this error (in the new version from pypi - 0.0.5)

```
Process Process-2:
Traceback (most recent call last):
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/site-packages/iterable_queue/iq.py", line 141, in manage_queue
    signal = consumers2manager_signals.get()
  File "<string>", line 2, in get
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
```

with that, another Broken Pipe error is creeping up : 

```
Process Process-10:
Traceback (most recent call last):
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/site-packages/cluster_func/_cf.py", line 702, in worker
    for args in args_consumer:
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/site-packages/iterable_queue/iq.py", line 256, in next
    return self.get(timeout=timeout)
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/site-packages/iterable_queue/iq.py", line 300, in get
    return_val = self.queue.get(block, timeout)
  File "<string>", line 2, in get
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
```

any ideas?

**Comment by enewe101** [comment] 2017-01-21 17:46
Nice find, I haven't encountered that before.  Could you post or send me
the minimal code needed to reproduce it?  Looks like something in the
iterable queue internals again.

On Jan 21, 2017 11:06 AM, "Koustuv Sinha" <notifications@github.com> wrote:

I am getting this error (in the new version from pypi - 0.0.5)

Process Process-2:
Traceback (most recent call last):
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/process.py",
line 258, in _bootstrap
    self.run()
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/process.py",
line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/site-packages/iterable_queue/iq.py",
line 141, in manage_queue
    signal = consumers2manager_signals.get()
  File "<string>", line 2, in get
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/managers.py",
line 759, in _callmethod
    kind, result = conn.recv()
EOFError

with that, another Broken Pipe error is creeping up :

Process Process-10:
Traceback (most recent call last):
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/process.py",
line 258, in _bootstrap
    self.run()
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/process.py",
line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/site-packages/cluster_func/_cf.py",
line 702, in worker
    for args in args_consumer:
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/site-packages/iterable_queue/iq.py",
line 256, in next
    return self.get(timeout=timeout)
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/site-packages/iterable_queue/iq.py",
line 300, in get
    return_val = self.queue.get(block, timeout)
  File "<string>", line 2, in get
  File "/home/ndg/users/ksinha4/miniconda2/lib/python2.7/multiprocessing/managers.py",
line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/enewe101/cluster-func/issues/3>, or mute the thread

**Comment by enewe101** [comment] 2017-02-02 20:14
I was able to reproduce an error like this, but in Python3.  That error is fixed in the latest version, so I think your issue is solved in v. 0.0.6

Feel free to re-open with a minimal code to reproduce your problem!

**Closed as completed by enewe101** 2017-02-02 20:14 UTC
