### ISSUE TITLE
exit handler for keyboard interrupt

### ISSUE THREAD

**Issue by koustuvsinha** [enewe101/cluster-func#1] opened 2017-01-16 20:19 UTC
while running multi processes, it would be helpful if cluf had an exit handling strategy for keyboard interrupts.

**Comment by enewe101** [comment] 2017-01-17 02:59
Great suggestion.  The problem is actually in the dependency `iterable-queue`.  I've been meaning to fix that, which has been preventing me from making the v1.0.0 release of `iterable-queue`.  It's now fixed by using `multiprocessing.Manager.Queue`s instead of `multiprocessing.Queue`s, which tend to get corrupted.

To get the fix, you'll actually need to upgrade your iterable-queue install to at least 1.0.0:

    $ pip install "iterable-queue>=1.0.0"

Let me know if that works for you.

**Comment by koustuvsinha** [comment] 2017-01-18 00:55
suggestion : can the `iterable-queue` dependency of v1.0.0 be specified in setup.py itself? that resolves the issue

**Comment by enewe101** [comment] 2017-01-18 02:45
Ah good idea!  Done.  So if you upgrade `cluster-func` it will now require the new version of `iterable-queue`.

**Closed as completed by enewe101** 2017-01-18 02:45 UTC
